name: 更新ip

on:
  # push
  schedule:
    - cron: '*/60 * * * *'  # 每 15 分钟执行一次
  workflow_dispatch: # Put here!!

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 指定 Python 版本
    
    - name: Install dependencies
      run: pip install -r requirements.txt  # 如果有依赖，需安装
      
    - name: Execute Python script and write output to file
      run: python main.py  # 运行你的 Python 脚本并将输出写入到文件 > output.txt

    - name: Commit and push
      run: |
        git config --local user.email "663809323@qq.com"
        git config --local user.name "1622663850"
        git add output.txt
        git commit -m "Update output.txt from GitHub Actions"
        git push origin main
